spring:
  application:
    name: create-spring-app
  docker:
    compose:
      enabled: true
  config:
    import: optional:file:create-spring-app.env[.properties]
  profiles:
    active: dev # 배포 시 prod 로 변경