# Docker Compose 개발용 yml
# 모든 서비스를 컨테이너로 실행

spring:
  application:
    name: ${PROJECT_NAME}
  docker:
    compose:
      enabled: true
      file: compose-dev.yaml
  jackson:
    time-zone: Asia/Seoul
  # DATASOURCE SETTING
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # REDIS SETTING
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # SECURITY SETTING
  security:
    cors:
      client:
        dev-cors-allowed-url: ${DEV_CORS_ALLOWED_URL} # 클라이언트 개발 서버 허용 URL
        prod-cors-allowed-url: ${PROD_CORS_ALLOWED_URL} # 프로덕션 개발 서버 허용 URL
    auth:
      use-session: ${USE_SESSION}
      jwt:
        secret: ${JWT_SECRET} # JWT SECRET
      permit-urls:
        - /api/v1/auth/sign-up
        - /api/v1/auth/login
        - /api/v1/auth/refresh
      base-url: /api/v1
      login-url: /api/v1/auth/login
      logout-url: /api/v1/auth/logout
      admin-url-pattern: /api/v1/admin/**
      user-url-pattern: /api/v1/user/**

# AES KEY
aes:
  aes-key: ${AES_KEY}

# LOGGING LEVEL
logging:
  level:
    site: debug
    org.springframework.data.redis: info
    io.lettuce.core: info

# FIREBASE SETTING
firebase:
  api-url:
  json-directory:

# SLACK BOT SETTING
slack:
  webhook:
    url:
  bot-token:
  channel-id:

# WHITE ERROR PAGE
server:
  error:
    whitelabel:
      enabled: false

datacenters:
  id: 1
servers:
  id: 1
