# 로컬 개발 테스트용 yml
# 로컬 머신 데이터베이스 접속 용도

spring:
  application:
    name: create-spring-app
  jackson:
    time-zone: Asia/Seoul
  # DATASOURCE SETTING
  datasource:
    url: jdbc:mysql://localhost:3306/create-spring-app?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # REDIS SETTING
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # SECURITY SETTING
  security:
    cors:
      client:
        dev-cors-allowed-url: http://localhost:3000 # 클라이언트 개발 서버 허용 URL
        prod-cors-allowed-url: your-service-url # 프로덕션 개발 서버 허용 URL
    auth:
      use-session: false
      jwt:
        secret: K9u1rZ5tQ8sB0xV7w3JcP2eR4yH6nL8aG5dF1mT9zW0xU7sQ3vE6pA2rN4tY8kL # JWT SECRET, 예시(변경 필요)

# AES KEY
aes:
  aes-key: Yv3sF9qA1nK7wL4eZ8pR2xC6tB0jM5uD # AES KEY 예시

# LOGGING LEVEL
logging:
  level:
    site: debug
    org.springframework.data.redis: info
    io.lettuce.core: info

# FIREBASE SETTING
firebase:
  api-url:
  json-directory:

# SLACK BOT SETTING
slack:
  webhook:
    url:
  bot-token:
  channel-id:

# WHITE ERROR PAGE
server:
  error:
    whitelabel:
      enabled: false

datacenters:
  id: 1
servers:
  id: 1
