spring:
  application:
    name: ${PROJECT_NAME}
  docker:
    compose:
      file: compose.yaml
  jackson:
    time-zone: Asia/Seoul
  # DATASOURCE SETTING
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # REDIS SETTING
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  jpa:
    show-sql: false # SQL 쿼리 출력 비활성화
    properties:
      hibernate:
        format_sql: false # 포맷된 SQL 출력 비활성화
  # SECURITY SETTING
  security:
    cors:
      client:
        dev-cors-allowed-url: ${DEV_CORS_ALLOWED_URL} # 클라이언트 개발 서버 허용 URL
        prod-cors-allowed-url: ${PROD_CORS_ALLOWED_URL} # 프로덕션 개발 서버 허용 URL
    auth:
      use-session: ${USE_SESSION}
      jwt:
        secret: ${JWT_SECRET} # JWT SECRET
      permit-urls:
        - /api/v1/auth/sign-up
        - /api/v1/auth/login
        - /api/v1/auth/refresh
      base-url: /api/v1
      login-url: /api/v1/auth/login
      logout-url: /api/v1/auth/logout
      admin-url-pattern: /api/v1/admin/**
      user-url-pattern: /api/v1/user/**

# AES KEY
aes:
  aes-key: ${AES_KEY}

# LOGGING LEVEL
logging:
  level:
    site: ${LOG_LEVEL}
    org.springframework.data.redis: ${REDIS_LOG_LEVEL}
    io.lettuce.core: ${REDIS_LETTUCE_LOG_LEVEL}

# FIREBASE SETTING
firebase:
  api-url: ${FIREBASE_API_URL}
  json-directory: ${FIREBASE_JSON_DIRECTORY}

# SLACK BOT SETTING
slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
  bot-token: ${SLACK_BOT_TOKEN}
  channel-id: ${SLACK_CHANNEL_ID}

# WHITE ERROR PAGE
server:
  error:
    whitelabel:
      enabled: false

datacenters:
  id: ${DATACENTER_ID}
servers:
  id: ${SERVER_ID}