# 로컬 개발 테스트용 yml
# 로컬 머신 데이터베이스 접속 용도

spring:
  application:
    name: ${PROJECT_NAME}
  docker:
    compose:
      file: compose-dev.yaml
  jackson:
    time-zone: Asia/Seoul
  # DATASOURCE SETTING
  datasource:
    url: jdbc:mysql://localhost:3306/create-spring-app?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # REDIS SETTING
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# AES KEY
aes:
  aes-key: ${AES_KEY}

# LOGGING LEVEL
logging:
  level:
    site: debug
    org.springframework.data.redis: info
    io.lettuce.core: info

# FIREBASE SETTING
firebase:
  api-url: ${FIREBASE_API_URL}
  json-directory: ${FIREBASE_JSON_DIRECTORY}

# SLACK BOT SETTING
slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
  bot-token: ${SLACK_BOT_TOKEN}
  channel-id: ${SLACK_CHANNEL_ID}

# WHITE ERROR PAGE
server:
  error:
    whitelabel:
      enabled: false

datacenters:
  id: ${DATACENTER_ID}
servers:
  id: ${SERVER_ID}
