spring:
  application:
    name: {PROJECT_APP}
  jackson:
    time-zone: Asia/Seoul
  # DATASOURCE SETTING
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # REDIS SETTING
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  jpa:
    show-sql: false # SQL 쿼리 출력 비활성화
    properties:
      hibernate:
        format_sql: false # 포맷된 SQL 출력 비활성화

# LOGGING LEVEL
logging:
  level:
    site: ${LOG_LEVEL}
    org.springframework.data.redis: ${REDIS_LOG_LEVEL}
    io.lettuce.core: ${REDIS_LETTUCE_LOG_LEVEL}

# FIREBASE SETTING
firebase:
  api-url: ${FIREBASE_API_URL}
  json-directory: ${FIREBASE_JSON_DIRECTORY}

# SLACK BOT SETTING
slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
  bot-token: ${SLACK_BOT_TOKEN}
  channel-id: ${SLACK_CHANNEL_ID}

# WHITE ERROR PAGE
server:
  error:
    whitelabel:
      enabled: false